version: "3.4"
services: 
    app:
        container_name: quiz
        restart: always
        env_file:
          - .env
        build:
          context: .
          network: host
        ports: 
          - "3000:9000"
        depends_on:
          - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db
