version: 2
jobs:
  build:
    working_directory: ~/quiz
    docker:
      - image: circleci/node:10.16.0
        environment:
          NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test